title: Carter Duong
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carterduong.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: carterduong

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-tidy

sass:
  sass_dir: _scss

exclude: 
  - cd.com4.code-workspace
  - feed.xml
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-metadata
  - img-full-res/
  - _config
  - deploy.sh

permalink: pretty

collections:
  projects:
    output: true
    order:
      - bitter-melon.md
      - sunset-spot-remix.md
      - fashion-quarterly.md
      - heavy-friends.md
      - resume.md
      - posters.md
      - extras.md