title: Carter Duong
baseurl: "/cd.com4" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: carterduong

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-tidy

sass:
  sass_dir: _scss

exclude: 
  - carterduong.com4.code-workspace
  - feed.xml
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-metadata

collections:
  projects:
    output: true
    order:
      - bitter-melon.md
      - sunset-spot.md
      - fashion-quarterly.md
      - heavy-friends.md
      - resume.md
      - posters.md
      - extras.md